Initial ICS support
lostcarpark/conclar pull request #171
Opened 2024-09-11 21:59 UTC by zoeimogen

Some basic ICS support, as requested in #132. (And by me several times in my own head during Worldcon, which is where I started work on this...)

Should be possible to add a "download all selected" without much further work but getting this in now while I have time.

2026-07-06 22:11 UTC, lostcarpark commented
Reviewed with @aJanuary today. Andrew wants to make minor tweaks, but this looks good to merge. Nice work.

2026-07-11 10:24 UTC, aJanuary commented
Thanks for this @zoeimogen

I have rebased this on the latest main, which has had some major changes (to deal with newer dependencies), so you'll need to do a `git reset --hard` on your local branch if you want to make further changes.

I also did some changes to the implementation:
 * Swap from `react-icalendar-link` to `ics` to generate the file. `react-icalendar-link` had some limitations in how we could configure it (couldn't add a title attribute, for example).
 * Lazily generate the ics contents on-demand rather than pre-computing them for every item.
 * Use the item title in the filename. I found I was getting my files muddled up very easily when I was testing without this.

2026-07-20 21:52 UTC, lostcarpark commented
Fixed merge conflict (just `import`s added to `ProgramItem` from both branches).

2026-07-20 22:07 UTC, lostcarpark requested changes
Looks great. I would just like the name of config entries updated. We don't need to duplicate CALENDARLINK in the child entries, and it will allow us to reuse schema elements when we add a JSON schema.

I realise this change is consistent with the PERMALINK entry, we might look at fixing that too at some point.

2026-07-20 22:07 UTC, lostcarpark commented on src/config_example.json
> +    "SHOW_CALENDARLINK": true,
Could we change `SHOW_CALENDARLINK` to just `SHOW`? This will keep it consistent with other config entries (where any consistency exists), and simplify adding a JSON schema to the config later.

2026-07-20 22:07 UTC, lostcarpark commented on src/config_example.json
> +    "CALENDARLINK_TITLE": "Add To Calendar"
Change `CALENDARLINK_TITLE` to `LABEL`, please. Again for consistency.

2026-07-20 22:07 UTC, lostcarpark commented on README.md
> +- `CALENDARLINK.CALENDARLINK`: "Title" text displayed when mouse is hovered over calendar download icon.
Update to match config change above, please.

2026-07-24 23:38 UTC, lostcarpark approved these changes
Looks perfect now.

2026-07-24 23:39 UTC, merged

2026-07-24 23:39 UTC, lostcarpark commented
Change merged. Thanks for your work on it.